---

name: disko-san
on: push

jobs:
  compile:
    name: Compile test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Compile
        run: make
