---

name: disko-san
on: push

jobs:
  runtest:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Compile
        run: make
      - name: Prepare disk
        run: truncate img -s 100MB
      - name: Run disko-san on img
        run: ./disko-san img stats
